### ISSUE TITLE
Should be able to run in a standalone repo without 'origin', too

### ISSUE THREAD

**Issue by nvie** [nvie/gitflow#11]

**Comment by rgabo** [comment]
especially as that's how we all would want to try it out before starting to git flow init a github cloned repository

**Comment by nvie** [comment]
N/A. git-flow does not require an origin since 0.2.

**Comment by nvie** [comment]
Hmm. This is broken indeed. Will look into this soon.

**Comment by gmallard** [comment]
What is the expected behavior of 'git flow init'?

Should it:

git checkout master
git checkout -b develop
git push origin develop

???

Or something even close to that ???

What if there is no 'origin' ??? How should it behave then?

Later:

A 'work around' seems to be:

git push origin develop

after the 'init'.

**Comment by nvie** [comment]
This is fixed in commit c118a85b44011a1ab102e40650b1e87a4d7254e9.
