### ISSUE TITLE
Missing bugfix branches 

### ISSUE THREAD

**Issue by mkurkov** [nvie/gitflow#24]
I wonnder why bugfix branches are missing in git flow. I think they are the same as features but with different prefix. Are they supposed to live in develop branch as commits without special branches?

**Comment by nvie** [comment]
Well, that's rather arbitrary. I don't think you should hang on to the term "feature" too tight. A rule of thumb would be that if you need more than one commit for a change, you should do it on a feature branch, otherwise commit it directly on develop.

Adding another flavour of branches would only make sense if it would be an actual other flavour. What you are referring to are simply feature branches (in that they branch off from develop and merge back into develop).

I would advise to name them "fix-" manually, for example:
    feature/fix-memory-crash

**Comment by mkurkov** [comment]
Thanks for clarifications.

**Comment by hokster7** [comment]
:+1:

**Comment by subtubes-io** [comment]
I came here with the same question. I understand the reasoning but the naming convention doesn't lend itself too well. I think adding "fix" might be something to consider? Just my 2 cents.

**Comment by hokster7** [comment]
@thiswildorchid I guess it is just convention. Bug fixes and features follow exactly the same process in git-flow. So for all intents and purposes `feature/fix-...` will work just fine...

**Comment by AMorgaut** [comment]
> @thiswildorchid I guess it is just convention. Bug fixes and features follow exactly the same process in git-flow. So for all intents and purposes `feature/fix-...` will work just fine...

I tend to disagree
According to your reference (https://jeffkreeftmeijer.com/git-flow/), release branches are meant to only accept bugfixes, not features. Git tooling could control this rule if a bugfix related naming convention is defined (and is respected)
and one without "feature" in the name would be less confusing in that context

**Comment by alejandroclaro** [comment]
My two cents.

The name is confusing, but the purpose make sense. There is no value or difference in having another prefix. The rules for such branches will be the same as feature branches.

Feature, or topic, branches are about planned changes. The nature of the change is not important.
