### ISSUE TITLE
How to bump version?

### ISSUE THREAD

**Issue by primeminister** [nvie/gitflow#26]
When I start a release branch:

```
$git flow release start release-1.1 1fe0166
Switched to a new branch 'release/release-1.1'

Summary of actions:
 - A new branch 'release/release-1.1' was created, based on '1fe0166'
 - You are now on branch 'release/release-1.1'

 Follow-up actions:
 - Bump the version number now!
 - Start committing last-minute fixes in preparing your release
 - When done, run:

      git flow release finish 'release-1.1'
```

I want to follow up and bump the version nmber. But why and how? Is it done automagically when I do finish ?

**Comment by nvie** [comment]
Bumping refers to the act of increasing your version number. As far as branches are concerned, gitflow does this automatically for you. But your application (or whatever you are versioning) probably wants to know which version it currently is. This is something that you still need to do manually, of course.

When gitflow reports that you should "bump your version number now", it means this: update your files manually so that they reflect the correct version number.

**Comment by primeminister** [comment]
He Vincent,
Dank je wel for the quick reply.
The scripts work great. Not sure how release branches etc works with remotes yet. I think that is still basic git.
Nogmaals Thanks!
- Charlie

**Comment by DahirWarsame** [comment]
<h1>Hi</h1>

I'm a bit new with _Git_ and i didn't really understand what you meant with manually update my files? Is there a command for that or do you mean just commit again.
Thanks in advance.

**Comment by airtonix** [comment]
@Dmaster420 no nvie actually means find the location in your code base where you might describe the version and increment it yourself.

for example, within my django applications I typically store the version in the base **init**.py file : 

https://github.com/airtonix/django-ikari/blob/master/ikari/__init__.py

then i use that in the setup.py: 

https://github.com/airtonix/django-ikari/blob/master/setup.py#L8

In my case, nvie is saying : "edit the **init**.py and change it from '0.0.8' to '0.0.9' (or whatever your release version is)

However there exists a forked version of git-flow that provides hooks where you can automate this.
