### ISSUE TITLE
When running "git flow init" in an already existing repository, it cannot detect the master branch

### ISSUE THREAD

**Issue by maxcrees** [nvie/gitflow#37]
The branch master exists. Even `git flow init` says it. But it says it doesn't exist anyway.

<pre>
rees@tardis ~/pyd $ git flow init

Which branch should be used for bringing forth production releases?
   - PY_3X
   - gh-pages
   - master
Branch name for production releases: [] master
Local branch 'master' does not exist.
</pre>

This is on Gentoo with git version 1.7.1 and git flow version 0.4-dev.

**Comment by nvie** [comment]
That's odd. Could you paste the output of the following command here?

```
DEBUG=yes git flow init
```

**Comment by maxcrees** [comment]
Sure. The output was quite lengthy, so I saved it to a file. The command that was run was:

```
echo "master" | DEBUG=yes git flow init &> git-flow.log.txt
```

And the output was saved [here](http://dev.sthrs.me/other/git-flow.log.txt).

**Comment by nvie** [comment]
This should be fixed in 871f5edee23fa4e00ba65d7295a8658eb4b895b6. Is was due to the fact that you probably have ANSI color output always enabled, even for non-TTY commands.

This patch shuts all color output of Git commands up.

**Comment by maxcrees** [comment]
Confirmed fix in 871f5edee23fa4e00ba65d7295a8658eb4b895b6.

**Comment by ikaschenko** [comment]
Had a problem while running "git flow init" on existing repo clone under win 7:

$ git flow init
C:\Program Files (x86)\Git\bin\git-flow: line 69: ./gitflow-common: No such file or directory
C:\Program Files (x86)\Git\bin\git-flow: line 78: ./gitflow-shFlags: No such file or directory

The problem was in wrong detection of current directory in "c:\Program Files (x86)\Git\bin\git-flow" file. A correction which allowed to work this around:
  a) comment line 45: # export GITFLOW_DIR=$(dirname "$0")
  b) added a line just after it with manually set abs path: export GITFLOW_DIR="c:\Program Files (x86)\Git\bin"

**Comment by jesalg** [comment]
Thanks @ikaschenko! I was having the same problem on Win7, your suggestion did the trick.
