### ISSUE TITLE
Set default branch for everything to "develop"

### ISSUE THREAD

**Issue by bart** [nvie/gitflow#392]
Hi everybody,

I have a short question. We are using a small adaption of gitflow, where everything will be branched from the develop branch, which means feature, bugfixes, releases and so far.

Is that possible?

**Comment by superole** [comment]
I'm not sure if you can set it as a default, since it kind of breaks the model, but you can define a different-from-default base for all the git flow branch types from the commandline e.g.:
git flow hotfix start 3.2.1 develop
I have never tested this though, and I fail to see any gain from this approach, but I don't judge you for trying something different. Feature and Release branches are already based on develop if you accepted the default value for "next release" development branch during init.

**Comment by bart** [comment]
In the meantime we decided to build and push the branches manually, thanks so far!
