### ISSUE TITLE
add support for annotated tags

### ISSUE THREAD

**Issue by snaewe** [nvie/gitflow#9]
Right now the git-flow-release script only creates 'light weight' tags.
It would be nice to be able to configure creation of annotated of even signed tags.

**Comment by nvie** [comment]
I'll put this one on the list, thanks for the addition.

**Comment by nvie** [comment]
Fixed in fafa2b28bec5b86fdf7f82e2d5b17880c98e5a1f.

**Comment by Hubro** [comment]
(Sorry in advance for commenting here if it's not the appropriate place)

I'm trying to get used to using `git flow hotfix` for fixing bugs found in production code. The annotated tags are really annoying me though. When running `git flow hotfix finish`, If I leave the tag message empty, the `finish` script crashes with the error:

> fatal: no tag message?
> Fatal: Tagging failed. Please run finish again to retry.

I'm not hyped about filling the tag annotation with random garbage for each hotfix release just because I have to. I'd much rather just use light tags like I always have.

Is it possible to instruct git flow to use light tags rather than annotated ones?
